# ABA 拓词策略默认阈值
DEFAULT_CLICK_SHARE_THRESHOLD = 0.20
DEFAULT_CONVERSION_SHARE_THRESHOLD = 0.16
DEFAULT_EFFICIENCY_THRESHOLD = 0.80
DEFAULT_DECAY = 0.30
DEFAULT_WEEKS = 8

# 用于历史 bid 微调的简单效率分界
HIGH_PERFORMANCE_EFFICIENCY = 1.00
LOW_PERFORMANCE_EFFICIENCY = DEFAULT_EFFICIENCY_THRESHOLD
